services:
  loki-feishu_webhook:
    container_name: loki-feishu_webhook
    image: your_repo/loki-feishu_webhook:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - FEISHU_WEBHOOK_URL=https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxxxxxxxx
      - FEISHU_SECRET=xxxxxxxxxxxxxxxxxxx
      - HOST=0.0.0.0
      - PORT=8000
      - MYSQL_HOST=xxxxxxxxxx
      - MYSQL_DB=xxxxx
      - MYSQL_USER=xxxxx
      - MYSQL_PSWD=xxxxxxxxxxx
    ports:
      - 8000:8000
